name: ${project.artifactId}
version: ${project.version}

author: BCCS-Team
authors: []
website: https://www.mcstats.net

softdepend: [CloudNetAPI, TimoCloudAPI]

main: net.mcstats2.bridge.server.bukkit.Core
commands:
  mcstats:
    usage: </command>
  info:
    usage: </command>
  kick:
    usage: </command>
  mute:
    usage: </command>
  ban:
    usage: </command>
  cmute:
    usage: </command>
  cban:
    usage: </command>
  unmute:
    usage: </command>
  unban:
    usage: </command>
  alt:
    usage: </command>