name: ${project.artifactId}
version: ${project.version}

author: BCCS-Team
authors: []
website: https://www.mcstats.net

softdepend: [CloudNetAPI, TimoCloudAPI]

main: net.mcstats2.bridge.server.bukkit.Core
commands:
  mcs:
  mcstats:
  tc:
  team:
  teamchat:
  pi:
  pinfo:
  playerinfo:
  kick:
  unmute:
  unban:
  mute:
  ban:
  cmute:
  cban:
  alt:
  report:
  reports:
  goto:
  jumpto: